# Generated by Django 6.0.2 on 2026-03-30 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('guests', models.PositiveIntegerField(default=1)),
                ('meal_category', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], default='breakfast', max_length=20)),
                ('meal_addon_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('meal_addon_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('special_requests', models.TextField(blank=True)),
                ('promo_code', models.CharField(blank=True, max_length=30)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('free_food_guests', models.PositiveIntegerField(default=2)),
                ('extra_guest_count', models.PositiveIntegerField(default=0)),
                ('extra_guest_fee_per_night', models.DecimalField(decimal_places=2, default=500, max_digits=10)),
                ('extra_guest_fee_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('gcash', 'GCash'), ('cash', 'Cash on Arrival'), ('card', 'Credit/Debit Card')], max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('discount_percent', models.PositiveIntegerField(default=20, help_text='Discount percentage e.g. 20 = 20%')),
                ('is_active', models.BooleanField(default=True)),
                ('max_uses', models.PositiveIntegerField(default=100)),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('room_type', models.CharField(choices=[('regular', 'Regular'), ('standard', 'Standard'), ('deluxe', 'Deluxe'), ('suite', 'Suite'), ('family', 'Family')], default='standard', max_length=20)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacity', models.PositiveIntegerField(default=2)),
                ('max_bookings', models.PositiveIntegerField(default=1, help_text='Max simultaneous bookings allowed for this room (usually 1).')),
                ('description', models.TextField(blank=True)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('image_url', models.URLField(blank=True)),
                ('room_image', models.FileField(blank=True, null=True, upload_to='room-images/')),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Maintenance')], default='available', max_length=20)),
                ('floor', models.PositiveIntegerField(default=1)),
                ('free_food_guest_limit', models.PositiveIntegerField(default=2)),
                ('extra_guest_fee_per_night', models.DecimalField(decimal_places=2, default=500, max_digits=10)),
                ('lunch_price_per_guest', models.DecimalField(decimal_places=2, default=250, max_digits=10)),
                ('dinner_price_per_guest', models.DecimalField(decimal_places=2, default=400, max_digits=10)),
                ('extra_guest_lunch_price_per_guest', models.DecimalField(decimal_places=2, default=250, max_digits=10)),
                ('extra_guest_dinner_price_per_guest', models.DecimalField(decimal_places=2, default=400, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['room_number'],
            },
        ),
        migrations.CreateModel(
            name='RoomRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
