# Generated by Codex on 2026-03-31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hotelroom", "0004_alter_booking_meal_category"),
    ]

    operations = []
