# Generated by Django 6.0.3 on 2026-03-31 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelroom', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='meal_category',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('both', 'Both')], default='breakfast', max_length=20),
        ),
    ]
