# Generated by Codex on 2026-03-31

import uuid

from django.db import migrations, models


def populate_booking_references(apps, schema_editor):
    Booking = apps.get_model("hotelroom", "Booking")
    Payment = apps.get_model("hotelroom", "Payment")

    for booking in Booking.objects.all().order_by("id"):
        if not booking.reference_number:
            booking.reference_number = f"PH-{uuid.uuid4().hex[:10].upper()}"
            booking.save(update_fields=["reference_number"])

    for payment in Payment.objects.select_related("booking").all():
        if not payment.reference_number:
            payment.reference_number = payment.booking.reference_number or f"PH-{uuid.uuid4().hex[:10].upper()}"
            payment.save(update_fields=["reference_number"])


class Migration(migrations.Migration):

    dependencies = [
        ("hotelroom", "0003_booking_reference_number"),
        ("hotelroom", "0004_booking_reference_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="reference_number",
            field=models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True),
        ),
        migrations.RunPython(populate_booking_references, migrations.RunPython.noop),
    ]
