# Generated by Django 6.0.3 on 2026-04-01 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelroom', '0006_booking_cancellation_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
